# Generated by Django 5.0 on 2024-07-31 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=20)),
                ('cost', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='res',
        ),
    ]
